spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:test;DATABASE_TO_UPPER=false;
      username: saaa
      password:
  sql:
    init:
      mode: always # ?? ??? ????? ??
      encoding: utf-8
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console